- name: install the latest version of nginx
  yum: name={{ item }} state=present
  with_items:
   - nginx
   - mod_ssl
  tags: nginx

- name: replace nginx.conf
  replace: dest="/etc/nginx/nginx.conf" regexp="{{ item.regexp }}" replace="{{ item.replace }}" 
  with_items: replace_vars
  tags: nginx

- name: revers proxy
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  tags: nginx

- name: Create nginx configuration file vhosts
  template: src=vhosts.conf.j2 dest=/etc/nginx/conf.d/{{ item.name }}.conf
  with_items: vhosts
  tags: nginx

- name: nginx vhosts directory
  file: path=/var/www/vhosts/{{ item.name }}/ state=directory owner=nginx group={{ shared_group }} mode=0775
  with_items: vhosts
  tags: nginx

- name: change owner
  file: path=/var/www/vhosts owner=root group=root mode=0755
  tags: nginx

- name: nginx vhosts cgi-bin
  file: path=/var/www/vhosts/{{ item.name }}/cgi-bin/ state=directory owner=nginx group={{ shared_group }} mode=2775
  with_items: vhosts
  tags: nginx

- name: nginx vhosts htdocs
  file: path=/var/www/vhosts/{{ item.name }}/htdocs/ state=directory owner=nginx group={{ shared_group }} mode=2775
  with_items: vhosts
  tags: nginx

- name: nginx vhosts logs
  file: path=/var/www/vhosts/{{ item.name }}/logs/ state=directory owner=nginx group={{ shared_group }} mode=2775
  with_items: vhosts
  tags: nginx

- name: create htpasswd
  htpasswd: path=/var/www/htpasswd name={{  mt.basic.user }} password={{ mt.basic.passwd }} owner=nginx group={{shared_group}} mode=0644
  tags: nginx

- name: modify nginx users
  user: name=nginx group={{shared_group}} groups=nginx append=yes
  tags: nginx

- name: logrotate.d for nginx
  template: src=nginx.j2 dest=/etc/logrotate.d/nginx
  tags: nginx

- name: nginx is runnning and enabled
  service: name=nginx state=running enabled=yes
  notify: restart nginx
  tags: nginx

