- name: Movable Type 8, MySQL8, Apache2.4 or Nginx, Perl5.36, Starman(PSGI), PHP8 installed 
  hosts: all
  gather_facts: True
  become: yes
  roles:
    - role: common
      tags: common
    - role: postfix
      tags: postfix
    - role: firewall
      tags: firewall
    - role: swap
      tags: swap
    - role: aws
      tags: aws
      when: al2023
    - role: mysqld
      tags: mysqld
      when: mysqld
    - role: letsencrypt
      tags: letsencrypt
      when: letsencrypt
    - role: nginx
      tags: nginx
      when: nginx
    - role: httpd
      tags: httpd
      when: apache
    - role: sshd
      tags: sshd
    - role: php
      tags: php 
      when: php
    - role: perl
      tags: perl
      when: movabletype
    - role: ImageMagick
      tags: ImageMagick
      when: ImageMagick
    - role: movabletype
      tags: movabletype
      when: movabletype
    - role: restart
      tags: restart
      when: apache or nginx
