- name: Movable Type6.3, MySQL5.7, Apache2.4 or Nginx, Starman(PSGI), PHP7(Apache only) installed 
  hosts: all
  gather_facts: True
  roles:
    - role: common
      tags: common
    - role: postfix
      tags: postfix
    - role: iptables
      tags: iptables
      when: (ansible_distribution == "CentOS" ) and ( ansible_distribution_major_version == "6")
    - role: firewall
      tags: firewall
      when: ((ansible_distribution == "CentOS" ) or (ansible_distribution == 'RedHat' )) and ( ansible_distribution_major_version == "7")
    - role: swap
      tags: swap
    - role: aws
      tags: aws
      when: ansible_distribution == "Amazon"
    - role: mysql
      tags: mysql 
    - role: letsencrypt
      tags: letsencrypt
      when: "{{ letsencrypt | bool }}"
    - role: nginx
      tags: nginx
      when: "{{ nginx | bool }}"
    - role: httpd
      tags: httpd
      when: "{{ apache | bool }}"
    - role: sshd
      tags: sshd
    - role: ImageMagick
      tags: ImageMagick
    - role: php
      tags: php 
      when: "{{ php | bool }}"
    - role: perl
      tags: perl 
      when: movabletype 
    - role: movabletype
      tags: movabletype
      when: movabletype 
    - role: supervisord
      tags: supervisord
  
