main_cf:
   - { regexp: '^#myhostname = (?:virtual|host).domain.tld$', replace: 'myhostname = {{ postfix.smtp.from | default(server_hostname) }}' }
   - { regexp: '^#mydomain = domain.tld$', replace: 'mydomain = {{  postfix.smtp.from | default(server_hostname) }}' }
   - { regexp: '^#myorigin = \$mydomain$', replace: 'myorigin = $mydomain' }
   - { regexp: '^inet_protocols = all$', replace: 'inet_protocols = ipv4' }
   - { regexp: '^mydestination = \$myhostname, localhost.\$mydomain, localhost$', replace: 'mydestination = localhost' }
   - { regexp: '^#mynetworks = 168.100.189.0/28, 127.0.0.0/8$', replace: 'mynetworks = 127.0.0.1' }
   - { regexp: '^smtp_tls_CAfile', replace: '#smtp_tls_CAfile' }
   - { regexp: '^smtp_tls_security_level', replace: '#smtp_tls_security_level' }
postconf: |
  relayhost = [{{ postfix.smtp.server }}]:{{ postfix.smtp.port }}
  smtp_sasl_auth_enable = yes
  smtp_sasl_security_options = noanonymous
  smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
  smtp_use_tls = yes
  smtp_tls_security_level = encrypt
  smtp_tls_note_starttls_offer = yes
  transport_maps = hash:/etc/postfix/transport
  smtp_tls_CAfile = /etc/ssl/certs/ca-bundle.crt
transport: |
  {{ root_email }} local:
  * :
files:
  - /etc/postfix/sasl_passwd
  - /etc/postfix/sasl_passwd.db
