- name: Show Swap and RAM
  debug: msg="ram={{ ansible_memtotal_mb }}, swap={{ ansible_swaptotal_mb }}"

- name: crete swap
  command: dd if=/dev/zero of=/mnt/swapfile bs=1M count={{ ansible_memtotal_mb }}
  when: "ansible_swaptotal_mb == 0" 
  tags: swap

- name: mkswap
  command: mkswap /mnt/swapfile
  when: "ansible_swaptotal_mb == 0" 
  tags: swap

- name: change permissions to swap
  file: path=/mnt/swapfile owner=root group=root mode=0600
  when: "ansible_swaptotal_mb == 0"
  tags: swap

- name: set swapon 
  command: swapon /mnt/swapfile
  when: "ansible_swaptotal_mb == 0 "
  tags: swap

- name:  mount swap
  mount: name=swap src=/mnt/swapfile fstype=swap opts=defaults passno=0 dump=0 state=present
  when: "ansible_swaptotal_mb == 0" 
  tags: swap
