php_ini_path: /etc/php.ini
php_package:
   - php
   - php-bcmath
   - php-cli
   - php-xml
   - php-common
   - php-devel
   - php-gd
   - php-json
   - php-mbstring
   - php-mysqlnd
   - php-opcache
   - php-pdo
   - php-pecl-mcrypt
   - php-pecl-memcached
