php_ini_path: /etc/opt/remi/php73/php.ini
php_package:
   - php73
   - php73-php
   - php73-php-mbstring
   - php73-php-mcrypt
   - php73-php-gd
   - php73-php-pdo
   - php73-php-opcache
   - php73-php-pecl-apcu
   - php73-php-mysqlnd
   - php73-php-pecl-apcu
   - php73-php-pecl-imagick
   - php73-php-pecl-memcache
   - php73-php-pecl-memcached
   - php73-php-pecl-mysql
   - php73-php-pecl-xdebug
   - php73-php-pecl-yaml
   - php73-php-xml

