- name: install the postfix
  dnf: name="postfix" state=present
  tags: postfix

- name: install the cyrus-sasl-plain
  dnf:
    name: "cyrus-sasl-plain"
    state: present
  tags: package
  ignore_errors: yes

- name: replace for main.cf
  replace: dest="/etc/postfix/main.cf" regexp="{{ item.regexp }}" replace="{{ item.replace }}" 
  with_items: "{{ main_cf }}"
  tags: postfix

- name: insert postfix configuation block in transport
  blockinfile:
    dest: /etc/postfix/transport
    block: "{{ transport }}"
    create: yes
    unsafe_writes: yes
    owner: root
  tags: postfix

- name: run postmap
  shell: postmap /etc/postfix/transport
  tags: postix

- name: add aliases
  lineinfile:
    path: /etc/aliases
    line: "root: {{ root_email }}"
    state: present
    insertafter: EOF
  tags: postix

- name: Create .forward to postfix
  template: src=forward.j2 dest=/root/.forward force=no
  tags: postfix

- name: run postalias
  command: postalias /etc/aliases
  tags: postix

- name: run newaliases
  command: newaliases
  tags: postix

- name: insert postfix configuation block in main.cf
  blockinfile:
    dest: /etc/postfix/main.cf
    block: "{{ postconf }}"
  when: postfix.relay | bool
  tags: postfix

- name: Create sasl_passwd to postfix
  template: src=sasl_passwd.j2 dest=/etc/postfix/sasl_passwd force=no
  when: postfix.relay | bool
  tags: postfix
 
- name: run postmap
  command: postmap hash:/etc/postfix/sasl_passwd
  when: postfix.relay | bool
  tags: postix

- name: change permission 
  file: path="{{ item }}" owner=root group=root mode=0600
  with_items: "{{ files }}"
  when: postfix.relay | bool
  tags: postix

- name: postifx is runnning and enabled
  service: name=postfix state=started enabled=yes
  tags: postix
