- name: installed supervisord
  command: easy_install supervisor 
  when: centos7 or rhel7 or amzn2
  tags: supervisord

- name: installed supervisord
  pip: name=supervisor 
  when: centos8 or rhel8
  tags: supervisord

- name: create the supervisord directory
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /var/log/supervisord
    - /etc/supervisord.d
  tags: supervisord

- name: create the mt directory
  file: path={{ item }} state=directory owner={{ owner }} group={{ owner }} mode=0755
  with_items:
    - /var/log/movabletype
    - /var/run/movabletype
  tags: supervisord

- name: Create Supervisord configuration file
  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf force=no
  tags: supervisord

- name: Create movabletype configuration file
  template: src=movabletype.ini.j2 dest=/etc/supervisord.d/movabletype.ini force=no
  tags: supervisord

- name: Create systemd configuration file
  template:
    src: supervisord.service.j2
    dest: /etc/systemd/system/supervisord.service
    mode: 644
    owner: root
    group: root
    force: no
  tags: supervisord

- name: Create movabletype run file
  template: src=run.sh.j2 dest=/var/www/mt_run.sh mode=0755 force=no
  tags: supervisord

- name: Create run-periodic-tasks run file
  template: src=rpt.sh.j2 dest=/var/www/mt_rpt.sh mode=0755 force=no
  tags: supervisord

- name: Create movabletype tmpfile.d
  template: src=movabletype.conf.j2 dest=/etc/tmpfiles.d/movabletype.conf mode=0755 force=no
  tags: supervisord

- name: start supervisord
  service:
    name: supervisord
    state: started
    enabled: True
  tags: supervisord

