locale: ja_JP.UTF-8
locale_code: ja 
zone: Asia/Tokyo
zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo
group:
  shared: contents
  sftponly: sftponly
movabletype: True
ImageMagick: False
letsencrypt: False
mysqld: True
basic:
  auth: False
postfix:
  relay: False
php: False
nginx: False
apache: False
amzn2: "{{ ansible_distribution_file_variety == \"Amazon\" and ansible_distribution_major_version == \"2\" }}"
centos7: "{{ ansible_distribution == \"CentOS\" and ansible_distribution_major_version == \"7\" }}"
centos8: "{{ ansible_distribution == \"CentOS\" and ansible_distribution_major_version == \"8\" }}"
rhel7: "{{ ansible_distribution == \"RedHat\" and ansible_distribution_major_version == \"7\" }}"
rhel8: "{{ ansible_distribution == \"RedHat\" and ansible_distribution_major_version == \"8\" }}"
centos_rhel: "{{ ansible_distribution == \"RedHat\" or ansible_distribution == \"CentOS\" }}"
