locale: ja_JP.UTF-8
locale_code: ja 
zone: Asia/Tokyo
zoneinfo_path: /usr/share/zoneinfo/Asia/Tokyo
group:
  shared: contents
  sftponly: sftponly
movabletype: True
perl: 
  version: 5.36
  version_full: 5.36.0
letsencrypt: False
mysqld: True
basic:
  auth: False
postfix:
  relay: False
php: False
nginx: False
apache: False
al2023: "{{ ansible_distribution_file_variety == \"Amazon\" and ansible_distribution_major_version == \"2023\" }}"
alma9: "{{ ansible_distribution == \"AlmaLinux\" and ansible_distribution_major_version == \"9\" }}"
rocky9: "{{ ansible_distribution == \"Rocky\" and ansible_distribution_major_version == \"9\" }}"
rhel9: "{{ ansible_distribution == \"RedHat\" and ansible_distribution_major_version == \"9\" }}"
el9: "{{ alma9 or rocky9 or rhel9 }}"
