- name: install the 'python-pip'
  yum: name="python-pip" state=present
  tags: package
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: python passlib installed
  command: pip install {{ item }}
  with_items:
    - passlib
    - MySQL-python
  tags: python

