- name: set locale to /etc/cloud/cloud.cfg
  lineinfile: 'dest=/etc/cloud/cloud.cfg line="locale: {{locale}}"'
  tags: aws

- name: set repo_upgrade to /etc/cloud/cloud.cfg
  lineinfile: 'dest=/etc/cloud/cloud.cfg regexp="repo_upgrade\:" line="repo_upgrade: {{repo_upgrade}}"'
  tags: aws

- name: aws configure directory
  file: path=/root/.aws state=directory owner=root group=root mode=0755
  tags: aws

- name: copy aws configure file with default region
  template: src=.aws_config.j2 dest=/root/.aws/config owner=root mode=0600
  tags: aws

- name: remove ntpdate
  yum:
    name: 
      - ntp
      - ntpdate
    state: absent
  tags: aws

- name: Install the chronyd
  yum: name=chrony state=present
  tags: aws

- name: chronyd is runnning and enabled
  service: name=chronyd state=started enabled=yes
  tags: aws
  
