- name: get selinux status
  shell: getenforce
  changed_when: False
  register: selinux_state
  tags: restart

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive
  when: selinux_state.stdout != 'Permissive'
  tags: restart

- name: reboot
  reboot:
  when: selinux_state.stdout != 'Permissive'
  tags: restart

- name: reboot
  meta: end_host
  when: selinux_state.stdout != 'Permissive'
  tags: restart

- name: httpd is runnning and enabled
  service:
    name: httpd
    state: started
    enabled: yes
  when: apache
  tags: restart

- name: nginx is runnning and enabled
  service: 
    name: nginx
    state: started
    enabled: yes
  when: nginx
  tags: restart

- name: php-fpm is runnning and enabled
  service:
    name: php-fpm
    state: started
    enabled: yes
  when: php
  tags: restart

- name: start movabletype service
  systemd:
    name: movabletype.service
    state: started
    enabled: True
  when: movabletype
  tags: restart

- name: start run-periodic-tasks service
  systemd:
    name: run-periodic-tasks.service
    state: started
    enabled: True
  when: movabletype
  tags: restart

