- name: copy MT.zip
  unarchive: src="{{mt.file}}" dest=/var/www/ owner="{{ owner }}" group=contents mode=0775 creates=/var/www/movabletype/
  tags: movabletype

- name: Move movabletype to mt
  command: mv /var/www/{{mt.ver}} /var/www/movabletype creates=/var/www/movabletype/
  tags: movabletype

- name: Install the mt-plugins
  copy: src="mt-plugins/{{ item }}" dest="/var/www/movabletype/plugins/" owner={{ owner }} group=contents mode=0775
  with_items:
    - "{{ mt.plugins | default([]) }}"
  when: mt.plugins is defined
  tags: mt-plugins

- name: Install the mt-static
  copy: src="mt-static/{{ item }}" dest="/var/www/movabletype/mt-static/" owner={{ owner }} group=contents mode=0775
  with_items:
    - "{{ mt.static | default([]) }}"
  when: mt.static is defined
  tags: mt-plugins

- name: replace mt-config
  template: src=mt-config.cgi.j2 dest=/var/www/movabletype/mt-config.cgi owner={{ owner }} group=contents mode=0775
  tags: movabletype

- name: replace mt-config
  shell: find . -name '*.cgi' | xargs perl -i -ple 's{\#!/usr/bin/perl\E}{\#!/usr/local/perl-5.18/bin/perl}g'
  args:
    chdir: /var/www/movabletype
  tags: movabletype

- name: replace for tools scripts
  shell: find . -type f | xargs perl -i -ple 's{\#!/usr/bin/perl\E}{\#!/usr/local/perl-5.18/bin/perl}g'
  args:
    chdir: /var/www/movabletype/tools
  tags: movabletype

- name: set run-periodic-tasks
  cron: name='run-periodic-tasks' job="cd /var/www/movabletype/; ./tools/run-periodic-tasks" minute="*/5" user="{{ owner }}" state=present
  tags: movabletype

- name: logrotate
  template: src=logrotate.d.mt.j2 dest=/etc/logrotate.d/movabletype owner=root group=root mode=0664
  tags: logrotate

