- name: ImageMagick is installed
  yum:
    name:
      - ImageMagick
      - ImageMagick-devel
    state: present 
  when: centos7 or amzn2
  tags: ImageMagick

- name: ImageMagick is installed
  yum:
    name:
      - ImageMagick
      - ImageMagick-devel
    state: present 
    enablerepo: rhel-7-server-rhui-optional-rpms
  when: rhel7
  tags: ImageMagick

- name: ImageMagick is installed
  yum:
    name:
      - ImageMagick
      - ImageMagick-devel
    state: present
    enablerepo: remi,epel,codeready-builder-for-rhel-8-rhui-rpms
  when: rhel8
  tags: ImageMagick

- name: ImageMagick is installed
  yum:
    name:
      - ImageMagick
      - ImageMagick-devel
    state: present
    enablerepo: remi,epel,PowerTools
  when: centos8
  tags: ImageMagick

# installed php-imagick
- name: php imagick installed
  yum: name=php-pecl-imagick state=present enablerepo=amzn2extra-php7.3
  when: amzn2 and php
  tags: php

- name: php imagick installed
  yum: name=php-imagick state=present enablerepo=epel,epel-modular,remi-safe,remi-modular,remi
  when: ( centos8 or rhel8 ) and php
  tags: php

- name: php imagick installed
  yum: name=php-imagick enablerepo=epel,remi-safe,remi,remi-php74 state=present
  when: ( centos7 or rhel7 ) and php
  tags: php

# security
- name: insert "Policymap" configuation block in /etc/ImageMagick/policy.xml
  blockinfile:
    dest: /etc/ImageMagick-6/policy.xml
    block: "{{ policymap }}"
  when: centos_rhel
  tags: ImageMagick

- name: insert "Policymap" configuation block in /etc/ImageMagick/policy.xml
  blockinfile:
    dest: /etc/ImageMagick/policy.xml
    block: "{{ policymap }}"
  when: amzn2
  tags: ImageMagick
