- name: xbuild downloaded
  get_url: url=https://github.com/tagomoris/xbuild/archive/master.zip dest=/tmp/xbuild.zip force=True
  tags: perl

- name: copy and unzip files
  unarchive: src=/tmp/xbuild.zip dest=/root/ copy=no
  tags: perl

- name: perl installed
  shell: |
    /root/xbuild-master/perl-install 5.18.2 /usr/local/perl-5.18
  tags: perl

- name: cpm module installed 
  shell: /usr/local/perl-5.18/bin/cpanm -nq App::cpm

- name: cpan module installed 
  shell: /usr/local/perl-5.18/bin/cpm install -g {{item}} 
  with_items:
   - DBI
   - DBD::mysql@4.046
   - Task::Plack
   - Test::TCP
   - HTML::Entities
   - Env
   - File::Which
   - LWP
   - LWP::Protocol::https
   - Crypt::SSLeay
   - Crypt::DSA
   - Cache::File
   - YAML
   - Time::HiRes
   - IO::Socket::SSL
   - Archive::Zip
   - Authen::SASL
   - IPC::Run
   - Archive::Tar
   - Digest::SHA1
   - IO::Stringy
   - XML::Parser
   - Imager
   - XMLRPC::Transport::HTTP::Plack
   - Net::Server::SS::PreFork
   - Net::SSLeay
   - Net::OAuth
   - Cache::Memcached
   - YAML::Syck
   - Fatal
   - XML::SAX::Expat
   - XML::SAX::ExpatXS
   - XML::LibXML
   - XML::LibXML::SAX
  tags: perl
