server_hostname:  "movabletype.local"
root_email: "root@localhost"
letsencrypt: False
denyhosts: False
php: True
nginx: False
apache: True
owner: "{% if apache | bool %}apache{% else %}nginx{% endif %}"
mt:
  file: MT7-R4603.zip
  ver: MT7-R4603
  psgi: True
  config: 
    - {name: 'AdminScript', value: 'mt.cgi'}
    - {name: 'ImageDriver', value: 'Imager'}
  plugins:
    - PageBute
    - PSGIRestart
  db:
    name: movabletype
    user: movabletype
    passwd: '@Mt6password'
    server: localhost
  basic:
    user: username
    passwd: password
vhosts:
  - name: movabletype.local
    letsencrypt: False
    ssl:
      use: False
      only: False
relay: False
postfix:  
  smtp:
    from: example.com
    server: email-smtp.us-east-1.amazonaws.com
    pass: sample 
    user: sample
    port: 587
