server_hostname:  "amzn2.local"
root_email: "root@localhost"
letsencrypt: False
php: False
ImageMagick: False
nginx: True
apache: False
owner: "{% if apache | bool %}apache{% else %}nginx{% endif %}"
basic:
  auth: False
  path: /
  user: user
  passwd: pass
mt:
  #require_ip:
  #  - 127.0.0.1
  file: MT7-R4701.zip
  ver: MT7-R4701
  psgi: True
  config: 
    - {name: 'AdminScript', value: 'admin'}
    - {name: 'ImageDriver', value: 'Imager'}
  plugins:
    - PageBute
    - PSGIRestart
  db:
    name: movabletype
    user: movabletype
    passwd: '@Mt6password'
    server: localhost
vhosts:
  - name: amzn2.local
    letsencrypt: False
    ssl:
      use: False
      only: False
postfix:  
  relay: False
  smtp:
    from: example.com
