server_hostname:  "rocky9.local"
root_email: "root@localhost"
apache: False
nginx: True
owner: "{% if apache | bool %}apache{% else %}nginx{% endif %}"
php: True
ImageMagick: True
mt:
  file: MT-8.0.2.zip
  ver: MT-8.0.2
  psgi: True
  config: 
    - {name: 'AdminScript', value: 'admin'}
    - {name: 'ImageDriver', value: "{% if ImageMagick | bool %}ImageMagick{% else %}Imager{% endif %}"}
  plugins:
    - PSGIRestart
  db:
    name: movabletype
    user: "{{ vault.mt.db.user }}"
    password: "{{  vault.mt.db.password }}"
    server: localhost
  email: noreply@example.com
postfix:  
  relay: False
  smtp:
    from: example.com 
vhosts:
  - name: rocky9.local
    letsencrypt: False
    ssl:
      use: False
      only: False
