server_hostname:  "movabletype.local"
root_email: "root@localhost"
letsencrypt: False
php: False
nginx: False
apache: True
owner: "{% if apache | bool %}apache{% else %}nginx{% endif %}"
mt:
  file: MT7-R4701.zip
  ver: MT7-R4701
  psgi: True
  config: 
    - {name: 'AdminScript', value: 'mt.cgi'}
    - {name: 'ImageDriver', value: 'Imager'}
  plugins:
    - PageBute
    - PSGIRestart
  db:
    name: movabletype
    user: movabletype
    passwd: '@Mt6password'
    server: localhost
  basic:
    user: username
    passwd: password
vhosts:
  - name: movabletype.local
    letsencrypt: False
    ssl:
      use: False
      only: False
postfix:  
  relay: False
  smtp:
    from: example.com
