server_hostname:  "movabletype.local"
root_email: "youremail@example.com"
letsencrypt: False
denyhosts: False
php: True
nginx: False
apache: True
owner: "{% if apache | bool %}apache{% else %}nginx{% endif %}"
mt:
  file: MTOS-5.2.13.zip
  ver: MTOS-5.2.13
  psgi: True
  config: 
    - {name: 'AdminScript', value: 'mt.cgi'}
    - {name: 'ImageDriver', value: 'Imager'}
  #plugins:
    #- PageBute
    #- PSGIRestart
  db:
    name: movabletype
    user: movabletype
    passwd: '@Mt6password'
    server: localhost
  basic:
    user: username
    passwd: password
vhosts:
  - name: movabletype.local
    letsencrypt: False
    ssl:
      use: False
      only: False
    email: youremail@example.com
