server_hostname: "cms.example.com"
root_email: "root@cms.example.com"
letsencrypt: True
apache: True
nginx: False
#php: True
#ImageMagick: True
owner: "{% if apache | bool %}apache{% else %}nginx{% endif %}"
#basic:
#  auth: True
#  path: /
#  user: user
#  passwd: pass
mt:
  #require_ip:
  #  - 127.0.0.1
  psgi: True
  file: MT7-R4701.zip
  ver: MT7-R4701
  plugins:
    - PSGIRestart
  config:
    - {name: 'AdminScript', value: 'admin'}
    - {name: 'ImageDriver', value: 'Imager'}
  db:
    name: movabletype 
    user: "{{ vault.mt.db.user }}"
    passwd: "{{  vault.mt.db.passwd }}"
    server: localhost
vhosts:
  - name: cms.example.com
    letsencrypt: True
    email: "alert+ssl@cms.example.com"
    ssl:
      use:  True
      only: True
      #crt: example.crt
      #key: example.key
      #ca_crt: example.ca.crt
postfix:
  relay: True
  smtp:
    from: "{{ vault.postfix.smtp.from }}"
    user: "{{ vault.postfix.smtp.user }}"
    pass: "{{ vault.postfix.smtp.pass }}"
    server: "{{ vault.postfix.smtp.server }}"
    port: "{{ vault.postfix.smtp.port }}"
ssh:
  users: "{{ vault.ssh.users }}"
mysql:
  root:
    password: "{{ vault.mysql.root.password }}"
