server_hostname:  "mt.examaple.com"
root_email: "alert@mt.example.com"
letsencrypt: True
denyhosts: True
php: False
nginx: True
apache: False
owner: "{% if apache | bool %}apache{% else %}nginx{% endif %}"
mt:
  file: MT-6.3.4.zip
  ver: MT-6.3.4
  psgi: True
  config:
    - {name: 'AdminScript', value: 'mt.cgi'}
    - {name: 'ImageDriver', value: 'Imager'}
  plugins:
    - PageBute
    - PSGIRestart
  db:
    name: movabletype
    user: movabletype
    passwd: 'ABC@123456example'
    server: localhost
  #basic:
  #  user: example
  #  passwd: example
relay: False
postfix:  
  smtp:
    from: example.com
    server: email-smtp.us-east-1.amazonaws.com
    pass: "パスワード"
    user: "ユーザ名"
    port: 587
vhosts:
  - name: mt.example.com
    letsencrypt: True
    ssl:
      use: True
      only: True
    email: "alert@mt.example.com"
wheel_users:
  - { name: admin_user, password: "openssl passwd -1 'passwd'でhash化したものを記載" }
ssh_users:
  - { name: ssh_user,   password: "openssl passwd -1 'passwd'でhash化したものを記載" }
sftp_users:
  - { name: sftp_user,  password: "openssl passwd -1 'passwd'でhash化したものを記載" }

