server_hostname: "cms.example.com"
root_email: "root@cms.example.com"
letsencrypt: True
#php: True
apache: True
owner: "{% if apache | bool %}apache{% else %}nginx{% endif %}"
#basic:
#  auth: True
#  path: /
#  user: user
#  passwd: pass
mt:
  #require_ip:
  #  - 127.0.0.1
  psgi: True
  file: MT7-R4701.zip
  ver: MT7-R4701
  plugins:
    - PSGIRestart
  config:
    - {name: 'AdminScript', value: 'admin'}
    - {name: 'ImageDriver', value: 'Imager'}
  db:
    name: movabletype
    user: movabletype
    passwd: 'passwdABC123$'
    server: localhost
vhosts:
  - name: cms.example.com
    letsencrypt: True
    ssl:
      use:  True
      only: True
      #crt: example.crt
      #key: example.key
      #ca_crt: example.ca.crt
    email: "alert@cms.example.com"
postfix:
  relay: True
  smtp:
    from: cms.example.com
    user: ACCESSKEY
    pass: ACCESS_SECRET
    server: SMTP_SERVER
    port: 587
ssh_users:
  - { name: wheel_user1,    group: "wheel",                password: "hash" }
  - { name: ssh_user1,      group: "{{ shared_group }}",   password: "hash" }
  - { name: sftponly_user1, group: "{{ sftponly_group }}", password: "hash" }
