# php

- name: vars for centos & redhat
  include_vars: centos_redhat.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == 'RedHat'
  tags: php

- name: vars for amazonlinux
  include_vars: amazonlinux.yml
  when: ansible_distribution == "Amazon"
  tags: php

- name: php installed
  yum: name={{ item }} enablerepo=epel,remi,remi-php70 state=present
  with_items: "{{ php_package }}"
  when: ansible_distribution == "CentOS"
  tags: php

- name: php installed
  yum: name={{ item }} enablerepo=epel,remi,remi-php70 state=present skip_broken=yes
  with_items: "{{ php_package }}"
  when: ansible_distribution == 'RedHat'
  tags: php

- name: php installed
  yum: name={{ item }} state=present
  with_items: "{{ php_package }}"
  when: ansible_distribution == "Amazon"
  tags: php

- name: phpini configured
  notify:
    - restart httpd
  lineinfile:
    dest: "{{ php_ini_path }}"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ php_ini }}"
  tags: phpini
