# php
- name: vars for el9
  include_vars: el9.yml
  when: el9
  tags: php

- name: vars for al2023
  include_vars: al2023.yml
  when: al2023
  tags: php

- name: php installed
  dnf:
    name: "{{ php_package }}"
    state: present
  tags: php

- name: change php-fpm settings
  lineinfile:
    dest: "{{ php_fpm_path }}"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ php_fpm }}"
  tags: php

- name: phpini configured
  lineinfile:
    dest: "{{ php_ini_path }}"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ php_ini }}"
  tags: php
