# php

- name: vars for centos & redhat
  include_vars: centos_redhat.yml
  when: centos7 or rhel7
  tags: php

- name: vars for centos & redhat
  include_vars: centos8_redhat8.yml
  when: centos8 or rhel8
  tags: php

- name: vars for amazonlinux
  include_vars: amazonlinux.yml
  when: amzn2
  tags: php

- name: enable amazon-linux-extras php73
  shell: 'amazon-linux-extras enable php7.3'
  when: amzn2
  tags: php

- name: php installed
  yum: name={{ php_package }} state=present enablerepo=amzn2extra-php7.3
  when: amzn2
  tags: php

- name: php installed
  yum: name=php-fpm state=present enablerepo=amzn2extra-php7.3
  when: amzn2 and nginx
  tags: php

- name: php installed
  shell: dnf --enablerepo=epel,epel-modular,remi-safe,remi-modular,remi module install -y php:remi-7.4
  when: centos8 or rhel8
  tags: php

- name: php installed
  yum: name={{ php_package }} state=present enablerepo=epel,epel-modular,remi-safe,remi-modular,remi
  when: centos8 or rhel8
  tags: php

- name: php installed
  yum: name={{ php_package }} enablerepo=epel,remi-safe,remi,remi-php74 state=present
  when: centos7 or rhel7
  tags: php

- name: php-fpm installed
  yum: name=php-fpm enablerepo=remi-php74 state=present
  when: centos7 or rhel7
  tags: php

- name: change php-fpm settings
  lineinfile:
    dest: "{{ php_fpm_path }}"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ php_fpm }}"
  when: (centos8 or rhel8 ) or nginx
  tags: php

- name: phpini configured
  lineinfile:
    dest: "{{ php_ini_path }}"
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
  with_items: "{{ php_ini }}"
  tags: php

