packages:
  - python-devel
  - apr-devel
  - apr-util-devel
  - aspell-devel
  - bison-devel
  - bzip2-devel
  - curl-devel
  - dstat
  - expect
  - giflib-devel
  - libX11-devel
  - libXext-devel
  - libXt-devel
  - libedit-devel
  - libevent-devel
  - libicu-devel
  - libjpeg-devel
  - libpng-devel
  - libtiff-devel
  - libtool-ltdl-devel
  - libwmf-devel
  - libxml2
  - libxml2-devel
  - libxslt-devel
  - logwatch
  - mlocate
  - mod_ssl
  - ncurses-devel
  - net-snmp-devel
  - nmap
  - openssl
  - openssl-devel
  - perl-ExtUtils-MakeMaker
  - perl-devel
  - postfix
  - readline-devel
  - rpm-build
  - sysstat
  - t1lib*
  - tcsh
  - telnet

