- name: downloaded letsencrypt
  get_url: url=https://dl.eff.org/certbot-auto dest=/opt/certbot-auto force=True mode=0755
  tags: letsencrypt
  when: centos_rhel

- name: LetsEncrypt installed
  yum: name="certbot-{{ owner }}" state=present enablerepo=epel
  tags: package
  when: amzn2

- name: create ssl
  command: /opt/certbot-auto certonly --keep-until-expiring --non-interactive --standalone -d "{{ item.name }}" --agree-tos -m "{{ item.email }}" --debug
  with_items: "{{ vhosts }}"
  tags: letsencrypt
  when: centos_rhel

- name: create ssl
  command: /bin/certbot certonly --keep-until-expiring --non-interactive --standalone -d "{{ item.name }}" --agree-tos -m "{{ item.email }}" --debug
  with_items: "{{ vhosts }}"
  tags: letsencrypt
  when: amzn2

- name: renew ssl 
  cron: name="letsencrypt auto renew {{ item.name }}" job="sudo /opt/certbot-auto certonly  --renew-by-default --webroot -n -w /var/www/vhosts/{{ item.name }}/htdocs -d {{ item.name }}" minute=0 hour=0 day=1 state=present
  with_items: "{{ vhosts }}"
  tags: letsencrypt

- name: httpd restart
  cron: name='ssl-renew-httpd-restart' job="service httpd restart" minute=10 hour=0 day=1 state=present
  tags: letsencrypt
  when: apache

- name: nginx restart
  cron: name='ssl-renew-nginx-restart' job="service nginx restart" minute=10 hour=0 day=1 state=present
  tags: letsencrypt
  when: nginx
