- name: create venv directory
  shell: sudo python3 -m venv /opt/certbot/
  tags: letsencrypt

- name: upgrade pip
  shell: sudo /opt/certbot/bin/pip install --upgrade pip
  tags: letsencrypt

- name: install pip-certbot
  shell: sudo /opt/certbot/bin/pip install certbot certbot
  tags: letsencrypt

- name: create link
  file:
    src: /opt/certbot/bin/certbot
    dest: /usr/bin/certbot
    state: link
  tags: letsencrypt

- name: create ssl
  command: /usr/bin/certbot certonly --keep-until-expiring --non-interactive --standalone -d "{{ item.name }}" --agree-tos -m "{{ item.email }}" --debug
  with_items: "{{ vhosts }}"
  tags: letsencrypt

- name: renew ssl 
  cron: name="letsencrypt auto renew {{ item.name }}" job="sudo certbot certonly  --renew-by-default --webroot -n -w /var/www/vhosts/{{ item.name }}/htdocs -d {{ item.name }}" minute=0 hour=0 day=1 state=present
  with_items: "{{ vhosts }}"
  tags: letsencrypt

- name: httpd restart
  cron: name='ssl-renew-httpd-restart' job="service httpd restart" minute=10 hour=0 day=1 state=present
  tags: letsencrypt
  when: apache

- name: nginx restart
  cron: name='ssl-renew-nginx-restart' job="service nginx restart" minute=10 hour=0 day=1 state=present
  tags: letsencrypt
  when: nginx
