- name: add mysql-repo for centos8 
  yum: name="https://dev.mysql.com/get/mysql80-community-release-el8-1.noarch.rpm" 
  tags: mysqld
  ignore_errors: yes
  when: centos8 or rhel8

- name: add mysql-repo for centos7 
  yum: name="https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm" 
  tags: mysqld
  ignore_errors: yes
  when: centos7 or rhel7 or amzn2

- name: disable repo
  replace: dest=/etc/yum.repos.d/mysql-community.repo regexp="enabled *= *1" replace="enabled=0"
  tags: mysqld

- name: disalbe repo mysql
  shell: 'dnf module disable -y mysql'
  tags: mysqld
  when: centos8 or rhel8

- name: Install Mysql package
  yum:
    name: "{{ packages }}"
    state: present
    enablerepo: mysql80-community
  tags: mysqld
  when: centos8 or rhel8

- name: Install Mysql package
  yum:
    name: "{{ packages }}"
    state: present
    enablerepo: mysql57-community
  tags: mysqld
  when: centos7 or rhel7 or amzn2

- name: install the 'python3-PyMySQL'
  dnf:
    name:
      - python36
      - python36-devel
      - python3-pip
      - python3-passlib
      - python3-PyMySQL
    state: latest
    enablerepo: epel
  when: centos8 or rhel8
  tags: mysqld

- name: install the 'python-pip'
  yum: name="python2-pip" state=present enablerepo=epel
  when: centos7 or rhel7 or amzn2
  tags: mysqld

- name: install the 'python-devel'
  yum: name="python-devel" state=present
  when: centos7 or rhel7
  tags: mysqld

- name: python passlib installed
  pip:
    name:
      - passlib
      - MySQL-python
  tags: mysqld
  when: centos7 or rhel7 or amzn2

- name: create mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  tags: mysqld

- name: start mysql service
  service: name=mysqld state=started enabled=yes
  tags: mysqld

- name: exists for /root/.my.cnf
  stat: path=/root/.my.cnf
  register: res
  tags: mysqld

- name: copy first root password
  shell: cat /var/log/mysqld.log | grep password | awk '{ print $NF }' | head -n 1
  register: mysql_passwd
  tags: mysqld
  when: not res.stat.exists

- name: set mysql root password
  shell: mysql --connect-expired-password -uroot -p'{{ mysql_passwd.stdout }}' --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql.root.password }}';"
  tags: mysqld
  when: not res.stat.exists

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600 force=no
  tags: mysqld
  when: not res.stat.exists

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host_all: yes
    password: "{{ mysql.root.password }}"
  tags: mysqld

- name: delete anonymous MySQL user
  mysql_user:
    name: ""
    host_all: yes
    state: absent
  tags: mysqld

- name: remove the MySQL test database
  mysql_db:
    db: test
    state: absent 
  tags: mysqld

- name: create database for mt
  mysql_db:
    db: "{{ mt.db.name }}"
    state: present
    encoding: utf8mb4
  tags: mysqld

- name: create database user
  mysql_user:
    name: "{{ mt.db.user }}"
    host: "{{ item }}"
    password: "{{ mt.db.passwd }}"
    priv: "{{ mt.db.name }}.*:ALL"
    state: present
  with_items:
   - "{{ ansible_hostname }}"
   - 127.0.0.1
   - ::1
   - localhost
  tags: mysqld

