- name: Install RPM-GPG-KEY-mysql
  rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
  tags: mysqld

- name: Install mysql-repo 
  dnf:
    name: "https://repo.mysql.com/mysql80-community-release-el9-1.noarch.rpm" 
    state: present
    disable_gpg_check: yes
  tags: mysqld
  ignore_errors: yes

- name: disable repo
  replace: dest=/etc/yum.repos.d/mysql-community.repo regexp="enabled *= *1" replace="enabled=0"
  tags: mysqld

- name: Install Mysql package
  dnf:
    name: "{{ packages }}"
    state: present
    enablerepo: mysql80-community
  tags: mysqld

- name: MySQL-Python installed
  pip:
    name:
      - PyMySQL
  tags: mysqld

- name: include my.cnf.d
  lineinfile: dest=/etc/my.cnf line="!includedir /etc/my.cnf.d"
  tags: mysqld

- name: create mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf.d/customize.cnf
  tags: mysqld

- name: exists for /root/.my.cnf
  stat: path=/root/.my.cnf
  register: res
  tags: mysqld

- name: clear passwd
  shell: mysqld --initialize-insecure
  tags: mysqld
  when: not res.stat.exists

- name: start mysql service
  service: name=mysqld state=started enabled=yes
  tags: mysqld

- name: set mysql root password
  shell: mysql --connect-expired-password -uroot --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mysql.root.password }}';"
  tags: mysqld
  when: not res.stat.exists

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600 force=no
  tags: mysqld
  when: not res.stat.exists

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host_all: yes
    password: "{{ mysql.root.password }}"
  tags: mysqld

- name: delete anonymous MySQL user
  mysql_user:
    name: ""
    host_all: yes
    state: absent
  tags: mysqld

- name: remove the MySQL test database
  mysql_db:
    db: test
    state: absent 
  tags: mysqld

